name: PR Builder

on:
  pull_request:
    branches: [main, master]
  workflow_dispatch:

env:
  MAVEN_OPTS: -Xmx4g -Xms1g

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
    
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@master
        with:
          args: 
            test

